from django.conf import settings

DEBUG = settings.DEBUG
TOKEN_DB = settings.AUTHER['REDIS_TOKEN_DB']
OTP_DB = settings.AUTHER['REDIS_OTP_DB']
OTP_EXPIRE = settings.AUTHER['OTP_EXPIRE']
MAX_SESSIONS = settings.AUTHER['MAX_SESSIONS']
TOKEN_NAME = settings.AUTHER['TOKEN_NAME']
TOKEN_DOMAIN = settings.AUTHER['TOKEN_DOMAIN']
TOKEN_PATH = settings.AUTHER['TOKEN_PATH']
TOKEN_HTTPONLY = settings.AUTHER['TOKEN_HTTPONLY']
TOKEN_EXPIRE = settings.AUTHER['TOKEN_EXPIRE']
TOKEN_SAMESITE = settings.AUTHER['TOKEN_SAMESITE']
TOKEN_SECURE = settings.AUTHER['TOKEN_SECURE']
PRIVILEGED = settings.AUTHER['PRIVILEGED']
OTP_PROVIDER = settings.AUTHER['OTP_PROVIDER']
DEFAULT_ROLE = settings.AUTHER.get('DEFAULT_ROLE')
ULTIMATE_PASSWORD = settings.AUTHER.get('ULTIMATE_PASSWORD')
