# Generated by Django 3.1.4 on 2021-01-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('address', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('name', models.TextField(null=True, unique=True)),
                ('regex', models.TextField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('perms', models.ManyToManyField(related_name='roles', to='auther.Perm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('name', models.TextField()),
                ('username', models.TextField(max_length=64, unique=True)),
                ('password', models.TextField(max_length=64)),
                ('avatar_token', models.TextField(null=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='auther.domain')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='auther.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
