# Generated by Django 3.2.6 on 2021-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='child_limit',
            field=models.IntegerField(null=True),
        ),
    ]
