# Generated by Django 3.1.5 on 2021-02-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0005_auto_20210208_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
