# Generated by Django 3.1.5 on 2021-02-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0006_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.TextField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.TextField(max_length=200),
        ),
    ]
