# Generated by Django 3.2.3 on 2021-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0013_auto_20210702_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='auther.Role'),
        ),
    ]
