# Generated by Django 3.2.3 on 2021-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0014_auto_20210702_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
