# Generated by Django 3.2.3 on 2021-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0015_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
