# Generated by Django 3.2.5 on 2021-07-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0016_alter_role_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='inserted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
