# Generated by Django 3.2.5 on 2021-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0017_auto_20210718_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=64, null=True, unique=True),
        ),
    ]
